# Generated by Django 2.2.12 on 2020-07-25 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appcat', '0002_auto_20200725_1056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('user_surname', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='UserGearRent',
            fields=[
                ('ug_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ug_rent_date', models.DateField()),
                ('ug_return_date', models.DateField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcat.GearCopy')),
                ('ug_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
