# Generated by Django 2.2.12 on 2020-07-25 10:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appcat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('year_of_production', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='GearCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gc_gear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcat.Gear')),
            ],
        ),
        migrations.CreateModel(
            name='GearStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gs_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
