# Generated by Django 2.2.12 on 2020-07-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcat', '0003_gear_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='image',
        ),
    ]
